### ISSUE TITLE
End-to-end integration / testing with leaderboard

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#932]
There's a few things that could be improved re: the [leaderboard](https://huggingface.co/spaces/mteb/leaderboard) & codebase integration 🤔

- We currently cannot automatically test the effect of changes made here on the leaderboard. This has caused a few issues: https://github.com/embeddings-benchmark/mteb/issues/903 ; https://github.com/embeddings-benchmark/mteb/issues/639
- The leaderboard requires manual refreshes (the benefit is that it allows us to do a quick manual check that all looks okay, but maybe automatic would still be better)
- Adding results via https://huggingface.co/datasets/mteb/results requires updating the `paths.json` file in there + adding the model specs to the leaderboard. Ideally, we would allow users to just submit all of this via PR and it would automatically update similar to how people add their models to alpaca, e.g. https://github.com/tatsu-lab/alpaca_eval/pull/342
- Reviewing [PRs on HF](https://huggingface.co/spaces/mteb/leaderboard/discussions?status=open&type=pull_request) does not yet work as well as on GitHub - it may be easier to take them on GitHub instead and auto-push them to the LB upon changes

cc @orionw who had some great ideas on this & is a GitHub actions wizard 🪄

**Comment by KennethEnevoldsen** [comment]
Completely agree! I would love to merge the two repositories!

**Comment by orionw** [comment]
+1 to this issue @Muennighoff!

I hope to take a look at the latter 3 of these bullet points at the end of next week: making it easier to add results / mirror to Github and calculate the leaderboard automatically without refreshes.

> We currently cannot automatically test the effect of changes made here on the leaderboard.

I was wondering about this myself - I think adding tests is a great starting place.  It is a little tricky as the solution to the latter three involves setting the leaderboard up as a mirror on Github and doing automatic pushes, so it would draw from the `main` branch of wherever we store the results (`mteb`?). So anyone doing a branch on `mteb` won't be able to see the failure until it's already committed.

One potential solution to this is to add another test to `mteb` that runs some part of the leaderboard processing code.  I think this could work, although it is not the cleanest solution (how do we sync that file so that updates to the leaderboard processing code are reflected to that test in mteb and vice versa).

**Comment by Muennighoff** [comment]
That's amazing! 🚀

I think ideally there'd be two tests, sth like:
1. Run a fast model on some datasets to get a result
2. Add the result to a toy results folder
3. Check if the leaderboard can fetch from that result folder

2. Turn the results into metadata
3. Check if the leaderboard can fetch from the metadata

I think we only need to make sure the leaderboard code runs without erroring out which could likely be done by just parametrizing it a bit and then we can feed in the results folder & metadata as parameters for the tests. Anyways, I think the best solution here will become clearer as we advance on the other issues 🤔

**Comment by KennethEnevoldsen** [comment]
> Wherever we store the results (mteb?)

I would add the results to `mteb`.

To avoid influencing the existing leaderboard too much it might be ideal to keep the existing one as is for now and create a new leaderboard for development.

**Comment by orionw** [comment]
> To avoid influencing the existing leaderboard too much it might be ideal to keep the existing one as is for now and create a new leaderboard for development.

Agree as I will likely break it a few times before it's fixed haha. I've created [mteb/leaderboard-in-progress](https://huggingface.co/spaces/mteb/leaderboard-in-progress) which we can rename when it's sync'd correctly.

**Comment by orionw** [comment]
I've created a [mteb/leaderboard](https://github.com/embeddings-benchmark/leaderboard/tree/main) Github which calculates the leaderboard results daily via Github actions (a full refresh) and syncs to the Huggingface Space [mteb/leaderboard-in-progress](https://huggingface.co/spaces/mteb/leaderboard-in-progress). The 1 hour refresh of all models can happen in the background at night while the space runs virtually instantaneously using those cached files! 

It'd be nice to monitor it for a days or two before making it work on the main space. For those couple days, is it okay to pause any new commits to the leaderboard space? I had to make a large number of refactors and it will be a pain to try to resolve new conflicts. 

Does Saturday/Sunday work for the switchover @Muennighoff? Trying to find a time that will cause the least impact if it goes down for a few hours during the transition and I'm not sure when the most active usage of the space is. 

NOTE: this doesn't use the new `mteb/results` Github -- what is the status of that?  Is that just MMTEB results?

**Comment by Muennighoff** [comment]
That's amazing! Your suggestion sounds good to me & we cannot commit anything for a few days (also cc @tomaarsen). I'm not sure it would even go down but any date is fine I think.

For the `mteb/results` GitHub - I think we can start using it? We just need to move over all result files from the `mteb/results` HF repo and then sync it I think?

**Comment by KennethEnevoldsen** [comment]
Yea I do think we should start using `mteb/results`. Instead of having multiple switches might it not be ideal to also add the interface update to MTEB as well?

Should we also add any updates on how to add models etc.?

**Comment by tomaarsen** [comment]
Seems good! I'll abstain from commits on the HF Leaderboard Space in the next few days.

- Tom Aarsen

**Comment by orionw** [comment]
> For the mteb/results GitHub - I think we can start using it? We just need to move over all result files from the mteb/results HF repo and then sync it I think?

Perfect, this seems like an easy thing to update then. I'll sync those also. 

> Yea I do think we should start using mteb/results. Instead of having multiple switches might it not be ideal to also add the interface update to MTEB as well?

Not sure what you mean by "interface update" - do you mean UI?  I was planning to just update the end-to-end stuff for now. 

> Should we also add any updates on how to add models etc.?

I think once everything is switched over this weekend we should turn off PRs to the Spaces and only enable PRs to the Github's (as they will propagate changes). I think it will make it slightly easier to manage also since the PR features on Github are more mature.

**Comment by KennethEnevoldsen** [comment]
> Not sure what you mean by "interface update" - do you mean UI @KennethEnevoldsen? I was planning to just update the end-to-end stuff for now.

Yea keep it as the CI stuff for now - I was getting to optimistic there

**Comment by orionw** [comment]
I went to merge the results Github with the results Space and realized there are some differences, perhaps because of changes to the scores?

The new results in the [Github](https://github.com/embeddings-benchmark/results/tree/master/intfloat__multilingual-e5-large/4dc6d853a804b9c8886ede6dda8a073b7dc08a81) are under {model_name}/{commit? or some hash}/{task_name}.json while the results [Space](https://huggingface.co/datasets/mteb/results/tree/main/results/gtr-t5-base) has them just {model_name}/{task_name}.json.

Is it okay if I get rid of that hash and stick the json files directly in the model folders, following the Space setup @KennethEnevoldsen? Wanted to check before I overwrite the repo.

**Comment by Muennighoff** [comment]
The hash is the model revision which I think we want to have going forward. You can just put a folder [no_revision_available](https://github.com/embeddings-benchmark/results/tree/master/intfloat__multilingual-e5-small/no_revision_available) for the HF results that don't have it

**Comment by orionw** [comment]
Ah, great - thanks!

**Comment by orionw** [comment]
I merged the Github repo and the Space repo and added the code that could sync them but I seem to not have full permissions on the [Github repo](https://github.com/embeddings-benchmark/results).  There are two steps for whomever has full permission:
- We need to add `HF_TOKEN` to secrets (can be any of our tokens as long as we have write access)
- We need to rename the main branch to `main` instead of `master` (the workflow expects `main` but I don't have permissions to change it)

I tested that the dataset can be loaded with the new revision-based paths and it appears to be working.

**Comment by orionw** [comment]
Thanks @KennethEnevoldsen! Turns out we ran out of GitHub LFS bandwidth quota.  Someone who has access to the `mteb` organization page, do you mind adding a screenshot of what is using it or adding me as an admin so I can check? It's in your main Github settings, click on billing and accounts, then switch to the mteb organization. 

It's a bit tricky since we don't want any git lfs on Github due to the small limit (1GB a month in bandwidth) but Huggingface forces us to use git-lfs for any file over 10MB.  I think we'll need to either split/compress files > 10MB or not mirror the repository, instead using it as a shell for processing only (downloading and executing some command).

**Comment by Muennighoff** [comment]
Added you I think!

**Comment by Muennighoff** [comment]
Yes, we definitely do not want to lose the discussions & likes 👍 The leaderboard (https://huggingface.co/spaces/mteb/leaderboard) does not have any git lfs files no? So why would some of the history need to be removed? 🤔

**Comment by orionw** [comment]
Sorry too many thoughts in that previous message. 

I added Git LFS files to the leaderboard Github a day or two ago so that that space no longer has to do any calculations (e.g. we never need to "refresh" it since the Github actions does it and caches it). But I am already removing the lfs files 🙃 and replacing with regular json files. That's minor though.

The part about force pushing to the leaderboard is to handle the syncing between Github and Huggingface Space. Right now the Github leaderboard repo syncs the daily updates to the leaderboard to the Huggingface [Leaderboard-in-progress space](https://huggingface.co/spaces/mteb/leaderboard-in-progress). However, we really want it to sync to the main leaderboard.

To get them to sync their Git histories have to be aligned. For Arena and Results this had to use force pushes because old Git LFS files in the history that couldn't be resolved make it impossible to regular merge. But you're right that the main Leaderboard has no Git LFS (and hopefully has never had them) so hopefully it's an easy merge.  Thanks for pointing that out, makes me feel better! If I can't do it with the regular merging I'll post again here and we can discuss.

**Comment by KennethEnevoldsen** [comment]
Thanks for doing this @orionw know from experience that CI like this that works across multiple repos can be a pain - seems like most things were resolved, but let know if there anything

**Comment by orionw** [comment]
Okay everything is syncing! 🎉

There are a few things we may want to do:
- Double check that the leaderboard has what we want. I noticed that there's a somewhat [repeat model](https://huggingface.co/tobchef/gte-Qwen2-1.5B-instruct-Q4_K_M-GGUF) (a GGUF version I think) that is now added with slightly worse scores than the original.  This is because any `mteb` tagged model will automatically show up on the leaderboard without our permission (but on the flip side, no need to "refresh" the leaderboard)
- Do we want to add any restrictions to commits to the `main` branches of these? Currently anyone with permission can commit to main. I'm not sure how `mteb` was setup but perhaps we want to duplicates these settings on `results` and `leaderboard` githubs.
- We should probably add more integration tests - what would we like to verify before people commits?
- We should not allow Huggingface Space/Dataset PRs. All PRs should go through the Githubs (cc @tomaarsen @KennethEnevoldsen @Muennighoff) I've added a warning on the results space but we should do something similar on the leaderboard space.

**Comment by Muennighoff** [comment]
Amazing work on this 🚀

1) Yeah whenever someone notices a duplicate we add it here: https://huggingface.co/spaces/mteb/leaderboard/blob/main/model_meta.yaml#L1238
2) "to the main branches of these" - Which repos do you mean with "these"?
3) Great point! I think we now want to allow people to submit PRs with their results & then automatically test that they can be loaded correctly and avoid having to manually update the `paths.json` file every time.
4) Nice feel free to open & pin a similar issue on the leaderboard space 👍

**Comment by orionw** [comment]
> Yeah whenever someone notices a duplicate we add it here:

Perfect, added it there on the Github and it should be gone from the leaderboard when it syncs in a few minutes. 

> Nice feel free to open & pin a similar issue on the leaderboard space 👍 (can also do it)

Done ✅ 

> "to the main branches of these" - Which repos do you mean with "these"?

The [results repo](https://github.com/embeddings-benchmark/results) and the [leaderboard repo](https://github.com/embeddings-benchmark/leaderboard). Right now anyone with access can commit to main, which I think is not allowed for the `mteb` repo? Perhaps I'm wrong though - I just want to make sure we have the same type of access controls on those as we do on `mteb`.

**Comment by KennethEnevoldsen** [comment]
> Right now anyone with access can commit to main, which I think is not allowed for the mteb repo? 

I believe it is allowed, but discouraged. We could def. set it up though on `mteb` we already have the branch protection set up for it.

as long as we are few enough with permission I don't think it is too much of a problem though.

**Comment by orionw** [comment]
> I believe it is allowed, but discouraged. We could def. set it up though on mteb we already have the branch protection set up for it.

Oh great, then we should be good to go then! Just wanted to make sure there was parity.

**Comment by KennethEnevoldsen** [comment]
Does that resolve this issue or do we still have some outstanding issues?

**Comment by orionw** [comment]
Perhaps it's a more broader term thing, but it'd be nice to have the regular `mteb` repo test that it can add a results file to the `results` repo and that it loads. That way if we ever change the format in `mteb` we know it still works. And we can add that loading test to the `results` repo as well.

Not entirely sure how we want to handle integration testing with the leaderboard. It would be nice to have some tests, but I'm not sure what they would be.

**Comment by KennethEnevoldsen** [comment]
So an approach could be to have an integration test that does the following:

1) from mteb main run a model on a representative set of tasks (we already do this in tests). 
2) integration test the app: Assuming that the app can "pull" its data from an arbitrary source (or that we can adapt it to do so), we can pull the app repo, point it to the newly created results folder, and see that we can start the app without errors (this only test that it runs).

re. integration test with `results` repo. This is (as I understand) just whether it loads using MTEBResults I believe we already have this test. Is there anything that I am missing here?

**Comment by orionw** [comment]
> This is (as I understand) just whether it loads using MTEBResults I believe we already have this test.

I meant that the results repo `results.py` script can read the values from the saved `MTEBResults` -- that's great news if we already have some version of that!

> So an approach could be to have an integration test that does the following:

I like this approach. I do think making sure the app runs after that whole process is the best we can do and it would test the whole range of the process (mteb, results, leaderboard) which is really nice.

**Comment by KennethEnevoldsen** [comment]
> I meant that the results repo results.py script can read the values from the saved MTEBResults -- that's great news if we already have some version of that!

Partly. Essentially running this function here should check the repo: https://github.com/embeddings-benchmark/mteb/blob/main/mteb/load_results/load_results.py#L79

Currently there is also some fixes in #1038 and in PRs to `results`. Should be doable to set up as a test. Would be good to have for PRs to the results repo.

**Comment by KennethEnevoldsen** [comment]
We have a smoke test for the leaderboard + we are more careful about testing when we have leaderboard changes. I will close this for now
